## These are defaults from Github Pages and cannot be altered
## I'm including them here for reference purposes only
## Source: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll

#lsi: false
#safe: true
#source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme

title: Trading Legend Solutions
logo: /assets/img/logo.png
description: Solutions to minigames and puzzles in Trading Legend
theme: jekyll-theme-minimal
